using CsvHelper;
using CsvHelper.Configuration;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using MathNet.Numerics.Distributions;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace DECS_Excel_Add_Ins
{
    // automatically generated by https://toolslick.com/generation/code/class-from-csv
    public class HpiModel
    {
        public ulong GEO_ID { get; set; }
        public string NAME { get; set; }
        public string county { get; set; }
        public int pop { get; set; }
        public double? pctgqtract { get; set; }
        public string UrbanType { get; set; }
        public double? LEB { get; set; }
        public double? LEB_pctile { get; set; }
        public double? hpi { get; set; }
        public double? hpi_pctile { get; set; }
        public int? hpi_quartile { get; set; }
        public string hpi_least_healthy_25pct { get; set; }
        public double? economic { get; set; }
        public double? economic_pctile { get; set; }
        public double? education { get; set; }
        public double? education_pctile { get; set; }
        public double? insurance { get; set; }
        public double? insurance_pctile { get; set; }
        public double? clean_enviro { get; set; }
        public double? clean_enviro_pctile { get; set; }
        public double? housing { get; set; }
        public double? housing_pctile { get; set; }
        public double? neighborhood { get; set; }
        public double? neighborhood_pctile { get; set; }
        public double? social { get; set; }
        public double? social_pctile { get; set; }
        public double? transportation { get; set; }
        public double? transportation_pctile { get; set; }
        public double? abovepoverty { get; set; }
        public double? abovepoverty_pctile { get; set; }
        public double? automobile { get; set; }
        public double? automobile_pctile { get; set; }
        public double? bachelorsed { get; set; }
        public double? bachelorsed_pctile { get; set; }
        public double? censusresponse { get; set; }
        public double? censusresponse_pctile { get; set; }
        public double? commute { get; set; }
        public double? commute_pctile { get; set; }
        public double? dieselpm { get; set; }
        public double? dieselpm_pctile { get; set; }
        public double? employed { get; set; }
        public double? employed_pctile { get; set; }
        public double? h20contam { get; set; }
        public double? h20contam_pctile { get; set; }
        public double? homeownership { get; set; }
        public double? homeownership_pctile { get; set; }
        public double? houserepair { get; set; }
        public double? houserepair_pctile { get; set; }
        public double? inhighschool { get; set; }
        public double? inhighschool_pctile { get; set; }
        public double? inpreschool { get; set; }
        public double? inpreschool_pctile { get; set; }
        public double? insured { get; set; }
        public double? insured_pctile { get; set; }
        public double? ownsevere { get; set; }
        public double? ownsevere_pctile { get; set; }
        public double? ozone { get; set; }
        public double? ozone_pctile { get; set; }
        public double? parkaccess { get; set; }
        public double? parkaccess_pctile { get; set; }
        public double? percapitaincome { get; set; }
        public double? percapitaincome_pctile { get; set; }
        public double? pm25 { get; set; }
        public double? pm25_pctile { get; set; }
        public double? rentsevere { get; set; }
        public double? rentsevere_pctile { get; set; }
        public double? retail { get; set; }
        public double? retail_pctile { get; set; }
        public double? treecanopy { get; set; }
        public double? treecanopy_pctile { get; set; }
        public double? uncrowded { get; set; }
        public double? uncrowded_pctile { get; set; }
        public double? voting { get; set; }
        public double? voting_pctile { get; set; }
        public double? latino_pct { get; set; }
        public double? white_pct { get; set; }
        public double? black_pct { get; set; }
        public double? asian_pct { get; set; }
        public double? multiple_pct { get; set; }
        public double? NativeAm_pct { get; set; }
        public double? PacificIsl_pct { get; set; }
        public double? other_pct { get; set; }
        public DateTime version { get; set; }
        public string notes { get; set; }
    }

    public class HpiModelClassMap : ClassMap<HpiModel>
    {
        public HpiModelClassMap()
        {
            Map(m => m.GEO_ID).Name("GEO_ID");
            Map(m => m.NAME).Name("NAME");
            Map(m => m.county).Name("county");
            Map(m => m.pop).Name("pop");
            Map(m => m.pctgqtract).Name("pctgqtract");
            Map(m => m.UrbanType).Name("UrbanType");
            Map(m => m.LEB).Name("LEB");
            Map(m => m.LEB_pctile).Name("LEB_pctile");
            Map(m => m.hpi).Name("hpi");
            Map(m => m.hpi_pctile).Name("hpi_pctile");
            Map(m => m.hpi_quartile).Name("hpi_quartile");
            Map(m => m.hpi_least_healthy_25pct).Name("hpi_least_healthy_25pct");
            Map(m => m.economic).Name("economic");
            Map(m => m.economic_pctile).Name("economic_pctile");
            Map(m => m.education).Name("education");
            Map(m => m.education_pctile).Name("education_pctile");
            Map(m => m.insurance).Name("insurance");
            Map(m => m.insurance_pctile).Name("insurance_pctile");
            Map(m => m.clean_enviro).Name("clean_enviro");
            Map(m => m.clean_enviro_pctile).Name("clean_enviro_pctile");
            Map(m => m.housing).Name("housing");
            Map(m => m.housing_pctile).Name("housing_pctile");
            Map(m => m.neighborhood).Name("neighborhood");
            Map(m => m.neighborhood_pctile).Name("neighborhood_pctile");
            Map(m => m.social).Name("social");
            Map(m => m.social_pctile).Name("social_pctile");
            Map(m => m.transportation).Name("transportation");
            Map(m => m.transportation_pctile).Name("transportation_pctile");
            Map(m => m.abovepoverty).Name("abovepoverty");
            Map(m => m.abovepoverty_pctile).Name("abovepoverty_pctile");
            Map(m => m.automobile).Name("automobile");
            Map(m => m.automobile_pctile).Name("automobile_pctile");
            Map(m => m.bachelorsed).Name("bachelorsed");
            Map(m => m.bachelorsed_pctile).Name("bachelorsed_pctile");
            Map(m => m.censusresponse).Name("censusresponse");
            Map(m => m.censusresponse_pctile).Name("censusresponse_pctile");
            Map(m => m.commute).Name("commute");
            Map(m => m.commute_pctile).Name("commute_pctile");
            Map(m => m.dieselpm).Name("dieselpm");
            Map(m => m.dieselpm_pctile).Name("dieselpm_pctile");
            Map(m => m.employed).Name("employed");
            Map(m => m.employed_pctile).Name("employed_pctile");
            Map(m => m.h20contam).Name("h20contam");
            Map(m => m.h20contam_pctile).Name("h20contam_pctile");
            Map(m => m.homeownership).Name("homeownership");
            Map(m => m.homeownership_pctile).Name("homeownership_pctile");
            Map(m => m.houserepair).Name("houserepair");
            Map(m => m.houserepair_pctile).Name("houserepair_pctile");
            Map(m => m.inhighschool).Name("inhighschool");
            Map(m => m.inhighschool_pctile).Name("inhighschool_pctile");
            Map(m => m.inpreschool).Name("inpreschool");
            Map(m => m.inpreschool_pctile).Name("inpreschool_pctile");
            Map(m => m.insured).Name("insured");
            Map(m => m.insured_pctile).Name("insured_pctile");
            Map(m => m.ownsevere).Name("ownsevere");
            Map(m => m.ownsevere_pctile).Name("ownsevere_pctile");
            Map(m => m.ozone).Name("ozone");
            Map(m => m.ozone_pctile).Name("ozone_pctile");
            Map(m => m.parkaccess).Name("parkaccess");
            Map(m => m.parkaccess_pctile).Name("parkaccess_pctile");
            Map(m => m.percapitaincome).Name("percapitaincome");
            Map(m => m.percapitaincome_pctile).Name("percapitaincome_pctile");
            Map(m => m.pm25).Name("pm25");
            Map(m => m.pm25_pctile).Name("pm25_pctile");
            Map(m => m.rentsevere).Name("rentsevere");
            Map(m => m.rentsevere_pctile).Name("rentsevere_pctile");
            Map(m => m.retail).Name("retail");
            Map(m => m.retail_pctile).Name("retail_pctile");
            Map(m => m.treecanopy).Name("treecanopy");
            Map(m => m.treecanopy_pctile).Name("treecanopy_pctile");
            Map(m => m.uncrowded).Name("uncrowded");
            Map(m => m.uncrowded_pctile).Name("uncrowded_pctile");
            Map(m => m.voting).Name("voting");
            Map(m => m.voting_pctile).Name("voting_pctile");
            Map(m => m.latino_pct).Name("latino_pct");
            Map(m => m.white_pct).Name("white_pct");
            Map(m => m.black_pct).Name("black_pct");
            Map(m => m.asian_pct).Name("asian_pct");
            Map(m => m.multiple_pct).Name("multiple_pct");
            Map(m => m.NativeAm_pct).Name("NativeAm_pct");
            Map(m => m.PacificIsl_pct).Name("PacificIsl_pct");
            Map(m => m.other_pct).Name("other_pct");
            Map(m => m.version).Name("version");
            Map(m => m.notes).Name("notes");
        }
    }

    internal class HpiTable
    {
        private Dictionary<ulong, HpiModel> hpiTable;

        internal bool ready { get; } = false;

        /// <summary>
        /// Gets file based on year
        /// <summary>
        /// <returns>string</returns>
        private string GetHpiFileName(string year)
        {
            string filePattern = string.Empty;

            switch (year)
            {
                case "2010":
                    filePattern = "hpi_2010.csv";
                    break;

                default:
                    throw new ArgumentOutOfRangeException(year, "Expected 2010.");
            }

            return filePattern;
        }

        internal HpiTable(string year)
        {
            hpiTable = new Dictionary<ulong, HpiModel>();
            var assembly = Assembly.GetExecutingAssembly();
            string filePattern = GetHpiFileName(year);
            var resourceName = assembly.GetManifestResourceNames().Single(str => str.EndsWith(filePattern));

            // https://joshclose.github.io/CsvHelper/getting-started/
            using (var reader = new StreamReader(assembly.GetManifestResourceStream(resourceName)))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                csv.Context.RegisterClassMap<HpiModelClassMap>();
                var records = csv.GetRecords<HpiModel>();

                foreach (var record in records)
                {
                    hpiTable.Add(record.GEO_ID, record);
                }
            }

            ready = hpiTable.Count > 0;
        }

        internal double? hpi(ulong fips)
        {
            try
            {
                return hpiTable[fips].hpi.Value;
            }
            catch (KeyNotFoundException)
            {
                return null;
            }
        }

        internal double? hpi_percentile(ulong fips)
        {
            try
            {
                return hpiTable[fips].hpi_pctile;
            }
            catch (KeyNotFoundException)
            {
                return null;
            }
        }
    }
}
