using CsvHelper;
using CsvHelper.Configuration;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Windows.Forms;

namespace DECS_Excel_Add_Ins
{
    public enum SviScope
    {
        [Description("California")]
        California = 1,
        [Description("USA")]
        USA = 2,
        [Description("Unknown")]
        Unknown = 0,
    }

    // automatically generated by https://toolslick.com/generation/code/class-from-csv
    public class SviModel
    {
        public int ST { get; set; }
        public string STATE { get; set; }
        public string ST_ABBR { get; set; }
        public int STCNTY { get; set; }
        public string COUNTY { get; set; }
        public ulong FIPS { get; set; }
        public string LOCATION { get; set; }
        public double AREA_SQMI { get; set; }
        public int E_TOTPOP { get; set; }
        public int M_TOTPOP { get; set; }
        public int E_HU { get; set; }
        public int M_HU { get; set; }
        public int E_HH { get; set; }
        public int M_HH { get; set; }
        public int E_POV150 { get; set; }
        public int M_POV150 { get; set; }
        public int E_UNEMP { get; set; }
        public int M_UNEMP { get; set; }
        public int E_HBURD { get; set; }
        public int M_HBURD { get; set; }
        public int E_NOHSDP { get; set; }
        public int M_NOHSDP { get; set; }
        public int E_UNINSUR { get; set; }
        public int M_UNINSUR { get; set; }
        public int E_AGE65 { get; set; }
        public int M_AGE65 { get; set; }
        public int E_AGE17 { get; set; }
        public int M_AGE17 { get; set; }
        public int E_DISABL { get; set; }
        public int M_DISABL { get; set; }
        public int E_SNGPNT { get; set; }
        public int M_SNGPNT { get; set; }
        public int E_LIMENG { get; set; }
        public int M_LIMENG { get; set; }
        public int E_MINRTY { get; set; }
        public int M_MINRTY { get; set; }
        public int E_MUNIT { get; set; }
        public int M_MUNIT { get; set; }
        public int E_MOBILE { get; set; }
        public int M_MOBILE { get; set; }
        public int E_CROWD { get; set; }
        public int M_CROWD { get; set; }
        public int E_NOVEH { get; set; }
        public int M_NOVEH { get; set; }
        public int E_GROUPQ { get; set; }
        public int M_GROUPQ { get; set; }
        public double EP_POV150 { get; set; }
        public double MP_POV150 { get; set; }
        public double EP_UNEMP { get; set; }
        public double MP_UNEMP { get; set; }
        public double EP_HBURD { get; set; }
        public double MP_HBURD { get; set; }
        public double EP_NOHSDP { get; set; }
        public double MP_NOHSDP { get; set; }
        public double EP_UNINSUR { get; set; }
        public double MP_UNINSUR { get; set; }
        public double EP_AGE65 { get; set; }
        public double MP_AGE65 { get; set; }
        public double EP_AGE17 { get; set; }
        public double MP_AGE17 { get; set; }
        public double EP_DISABL { get; set; }
        public double MP_DISABL { get; set; }
        public double EP_SNGPNT { get; set; }
        public double MP_SNGPNT { get; set; }
        public double EP_LIMENG { get; set; }
        public double MP_LIMENG { get; set; }
        public double EP_MINRTY { get; set; }
        public double MP_MINRTY { get; set; }
        public double EP_MUNIT { get; set; }
        public double MP_MUNIT { get; set; }
        public double EP_MOBILE { get; set; }
        public double MP_MOBILE { get; set; }
        public double EP_CROWD { get; set; }
        public double MP_CROWD { get; set; }
        public double EP_NOVEH { get; set; }
        public double MP_NOVEH { get; set; }
        public double EP_GROUPQ { get; set; }
        public double MP_GROUPQ { get; set; }
        public double EPL_POV150 { get; set; }
        public double EPL_UNEMP { get; set; }
        public double EPL_HBURD { get; set; }
        public double EPL_NOHSDP { get; set; }
        public double EPL_UNINSUR { get; set; }
        public double SPL_THEME1 { get; set; }
        public double RPL_THEME1 { get; set; }
        public double EPL_AGE65 { get; set; }
        public double EPL_AGE17 { get; set; }
        public double EPL_DISABL { get; set; }
        public double EPL_SNGPNT { get; set; }
        public double EPL_LIMENG { get; set; }
        public double SPL_THEME2 { get; set; }
        public double RPL_THEME2 { get; set; }
        public double EPL_MINRTY { get; set; }
        public double SPL_THEME3 { get; set; }
        public double RPL_THEME3 { get; set; }
        public double EPL_MUNIT { get; set; }
        public double EPL_MOBILE { get; set; }
        public double EPL_CROWD { get; set; }
        public double EPL_NOVEH { get; set; }
        public double EPL_GROUPQ { get; set; }
        public double SPL_THEME4 { get; set; }
        public double RPL_THEME4 { get; set; }
        public double SPL_THEMES { get; set; }
        public double RPL_THEMES { get; set; }
        public int F_POV150 { get; set; }
        public int F_UNEMP { get; set; }
        public int F_HBURD { get; set; }
        public int F_NOHSDP { get; set; }
        public int F_UNINSUR { get; set; }
        public int F_THEME1 { get; set; }
        public int F_AGE65 { get; set; }
        public int F_AGE17 { get; set; }
        public int F_DISABL { get; set; }
        public int F_SNGPNT { get; set; }
        public int F_LIMENG { get; set; }
        public int F_THEME2 { get; set; }
        public int F_MINRTY { get; set; }
        public int F_THEME3 { get; set; }
        public int F_MUNIT { get; set; }
        public int F_MOBILE { get; set; }
        public int F_CROWD { get; set; }
        public int F_NOVEH { get; set; }
        public int F_GROUPQ { get; set; }
        public int F_THEME4 { get; set; }
        public int F_TOTAL { get; set; }
        public int E_DAYPOP { get; set; }
        public int E_NOINT { get; set; }
        public int M_NOINT { get; set; }
        public int E_AFAM { get; set; }
        public int M_AFAM { get; set; }
        public int E_HISP { get; set; }
        public int M_HISP { get; set; }
        public int E_ASIAN { get; set; }
        public int M_ASIAN { get; set; }
        public int E_AIAN { get; set; }
        public int M_AIAN { get; set; }
        public int E_NHPI { get; set; }
        public int M_NHPI { get; set; }
        public int E_TWOMORE { get; set; }
        public int M_TWOMORE { get; set; }
        public int E_OTHERRACE { get; set; }
        public int M_OTHERRACE { get; set; }
        public double EP_NOINT { get; set; }
        public double MP_NOINT { get; set; }
        public double EP_AFAM { get; set; }
        public double MP_AFAM { get; set; }
        public double EP_HISP { get; set; }
        public double MP_HISP { get; set; }
        public double EP_ASIAN { get; set; }
        public double MP_ASIAN { get; set; }
        public double EP_AIAN { get; set; }
        public double MP_AIAN { get; set; }
        public double EP_NHPI { get; set; }
        public double MP_NHPI { get; set; }
        public double EP_TWOMORE { get; set; }
        public double MP_TWOMORE { get; set; }
        public double EP_OTHERRACE { get; set; }
        public double MP_OTHERRACE { get; set; }
    }

    public class SviModelClassMap : ClassMap<SviModel>
    {
        public SviModelClassMap()
        {
            Map(m => m.ST).Name("ST");
            Map(m => m.STATE).Name("STATE");
            Map(m => m.ST_ABBR).Name("ST_ABBR");
            Map(m => m.STCNTY).Name("STCNTY");
            Map(m => m.COUNTY).Name("COUNTY");
            Map(m => m.FIPS).Name("FIPS");
            Map(m => m.LOCATION).Name("LOCATION");
            Map(m => m.AREA_SQMI).Name("AREA_SQMI");
            Map(m => m.E_TOTPOP).Name("E_TOTPOP");
            Map(m => m.M_TOTPOP).Name("M_TOTPOP");
            Map(m => m.E_HU).Name("E_HU");
            Map(m => m.M_HU).Name("M_HU");
            Map(m => m.E_HH).Name("E_HH");
            Map(m => m.M_HH).Name("M_HH");
            Map(m => m.E_POV150).Name("E_POV150");
            Map(m => m.M_POV150).Name("M_POV150");
            Map(m => m.E_UNEMP).Name("E_UNEMP");
            Map(m => m.M_UNEMP).Name("M_UNEMP");
            Map(m => m.E_HBURD).Name("E_HBURD");
            Map(m => m.M_HBURD).Name("M_HBURD");
            Map(m => m.E_NOHSDP).Name("E_NOHSDP");
            Map(m => m.M_NOHSDP).Name("M_NOHSDP");
            Map(m => m.E_UNINSUR).Name("E_UNINSUR");
            Map(m => m.M_UNINSUR).Name("M_UNINSUR");
            Map(m => m.E_AGE65).Name("E_AGE65");
            Map(m => m.M_AGE65).Name("M_AGE65");
            Map(m => m.E_AGE17).Name("E_AGE17");
            Map(m => m.M_AGE17).Name("M_AGE17");
            Map(m => m.E_DISABL).Name("E_DISABL");
            Map(m => m.M_DISABL).Name("M_DISABL");
            Map(m => m.E_SNGPNT).Name("E_SNGPNT");
            Map(m => m.M_SNGPNT).Name("M_SNGPNT");
            Map(m => m.E_LIMENG).Name("E_LIMENG");
            Map(m => m.M_LIMENG).Name("M_LIMENG");
            Map(m => m.E_MINRTY).Name("E_MINRTY");
            Map(m => m.M_MINRTY).Name("M_MINRTY");
            Map(m => m.E_MUNIT).Name("E_MUNIT");
            Map(m => m.M_MUNIT).Name("M_MUNIT");
            Map(m => m.E_MOBILE).Name("E_MOBILE");
            Map(m => m.M_MOBILE).Name("M_MOBILE");
            Map(m => m.E_CROWD).Name("E_CROWD");
            Map(m => m.M_CROWD).Name("M_CROWD");
            Map(m => m.E_NOVEH).Name("E_NOVEH");
            Map(m => m.M_NOVEH).Name("M_NOVEH");
            Map(m => m.E_GROUPQ).Name("E_GROUPQ");
            Map(m => m.M_GROUPQ).Name("M_GROUPQ");
            Map(m => m.EP_POV150).Name("EP_POV150");
            Map(m => m.MP_POV150).Name("MP_POV150");
            Map(m => m.EP_UNEMP).Name("EP_UNEMP");
            Map(m => m.MP_UNEMP).Name("MP_UNEMP");
            Map(m => m.EP_HBURD).Name("EP_HBURD");
            Map(m => m.MP_HBURD).Name("MP_HBURD");
            Map(m => m.EP_NOHSDP).Name("EP_NOHSDP");
            Map(m => m.MP_NOHSDP).Name("MP_NOHSDP");
            Map(m => m.EP_UNINSUR).Name("EP_UNINSUR");
            Map(m => m.MP_UNINSUR).Name("MP_UNINSUR");
            Map(m => m.EP_AGE65).Name("EP_AGE65");
            Map(m => m.MP_AGE65).Name("MP_AGE65");
            Map(m => m.EP_AGE17).Name("EP_AGE17");
            Map(m => m.MP_AGE17).Name("MP_AGE17");
            Map(m => m.EP_DISABL).Name("EP_DISABL");
            Map(m => m.MP_DISABL).Name("MP_DISABL");
            Map(m => m.EP_SNGPNT).Name("EP_SNGPNT");
            Map(m => m.MP_SNGPNT).Name("MP_SNGPNT");
            Map(m => m.EP_LIMENG).Name("EP_LIMENG");
            Map(m => m.MP_LIMENG).Name("MP_LIMENG");
            Map(m => m.EP_MINRTY).Name("EP_MINRTY");
            Map(m => m.MP_MINRTY).Name("MP_MINRTY");
            Map(m => m.EP_MUNIT).Name("EP_MUNIT");
            Map(m => m.MP_MUNIT).Name("MP_MUNIT");
            Map(m => m.EP_MOBILE).Name("EP_MOBILE");
            Map(m => m.MP_MOBILE).Name("MP_MOBILE");
            Map(m => m.EP_CROWD).Name("EP_CROWD");
            Map(m => m.MP_CROWD).Name("MP_CROWD");
            Map(m => m.EP_NOVEH).Name("EP_NOVEH");
            Map(m => m.MP_NOVEH).Name("MP_NOVEH");
            Map(m => m.EP_GROUPQ).Name("EP_GROUPQ");
            Map(m => m.MP_GROUPQ).Name("MP_GROUPQ");
            Map(m => m.EPL_POV150).Name("EPL_POV150");
            Map(m => m.EPL_UNEMP).Name("EPL_UNEMP");
            Map(m => m.EPL_HBURD).Name("EPL_HBURD");
            Map(m => m.EPL_NOHSDP).Name("EPL_NOHSDP");
            Map(m => m.EPL_UNINSUR).Name("EPL_UNINSUR");
            Map(m => m.SPL_THEME1).Name("SPL_THEME1");
            Map(m => m.RPL_THEME1).Name("RPL_THEME1");
            Map(m => m.EPL_AGE65).Name("EPL_AGE65");
            Map(m => m.EPL_AGE17).Name("EPL_AGE17");
            Map(m => m.EPL_DISABL).Name("EPL_DISABL");
            Map(m => m.EPL_SNGPNT).Name("EPL_SNGPNT");
            Map(m => m.EPL_LIMENG).Name("EPL_LIMENG");
            Map(m => m.SPL_THEME2).Name("SPL_THEME2");
            Map(m => m.RPL_THEME2).Name("RPL_THEME2");
            Map(m => m.EPL_MINRTY).Name("EPL_MINRTY");
            Map(m => m.SPL_THEME3).Name("SPL_THEME3");
            Map(m => m.RPL_THEME3).Name("RPL_THEME3");
            Map(m => m.EPL_MUNIT).Name("EPL_MUNIT");
            Map(m => m.EPL_MOBILE).Name("EPL_MOBILE");
            Map(m => m.EPL_CROWD).Name("EPL_CROWD");
            Map(m => m.EPL_NOVEH).Name("EPL_NOVEH");
            Map(m => m.EPL_GROUPQ).Name("EPL_GROUPQ");
            Map(m => m.SPL_THEME4).Name("SPL_THEME4");
            Map(m => m.RPL_THEME4).Name("RPL_THEME4");
            Map(m => m.SPL_THEMES).Name("SPL_THEMES");
            Map(m => m.RPL_THEMES).Name("RPL_THEMES");
            Map(m => m.F_POV150).Name("F_POV150");
            Map(m => m.F_UNEMP).Name("F_UNEMP");
            Map(m => m.F_HBURD).Name("F_HBURD");
            Map(m => m.F_NOHSDP).Name("F_NOHSDP");
            Map(m => m.F_UNINSUR).Name("F_UNINSUR");
            Map(m => m.F_THEME1).Name("F_THEME1");
            Map(m => m.F_AGE65).Name("F_AGE65");
            Map(m => m.F_AGE17).Name("F_AGE17");
            Map(m => m.F_DISABL).Name("F_DISABL");
            Map(m => m.F_SNGPNT).Name("F_SNGPNT");
            Map(m => m.F_LIMENG).Name("F_LIMENG");
            Map(m => m.F_THEME2).Name("F_THEME2");
            Map(m => m.F_MINRTY).Name("F_MINRTY");
            Map(m => m.F_THEME3).Name("F_THEME3");
            Map(m => m.F_MUNIT).Name("F_MUNIT");
            Map(m => m.F_MOBILE).Name("F_MOBILE");
            Map(m => m.F_CROWD).Name("F_CROWD");
            Map(m => m.F_NOVEH).Name("F_NOVEH");
            Map(m => m.F_GROUPQ).Name("F_GROUPQ");
            Map(m => m.F_THEME4).Name("F_THEME4");
            Map(m => m.F_TOTAL).Name("F_TOTAL");
            Map(m => m.E_DAYPOP).Name("E_DAYPOP");
            Map(m => m.E_NOINT).Name("E_NOINT");
            Map(m => m.M_NOINT).Name("M_NOINT");
            Map(m => m.E_AFAM).Name("E_AFAM");
            Map(m => m.M_AFAM).Name("M_AFAM");
            Map(m => m.E_HISP).Name("E_HISP");
            Map(m => m.M_HISP).Name("M_HISP");
            Map(m => m.E_ASIAN).Name("E_ASIAN");
            Map(m => m.M_ASIAN).Name("M_ASIAN");
            Map(m => m.E_AIAN).Name("E_AIAN");
            Map(m => m.M_AIAN).Name("M_AIAN");
            Map(m => m.E_NHPI).Name("E_NHPI");
            Map(m => m.M_NHPI).Name("M_NHPI");
            Map(m => m.E_TWOMORE).Name("E_TWOMORE");
            Map(m => m.M_TWOMORE).Name("M_TWOMORE");
            Map(m => m.E_OTHERRACE).Name("E_OTHERRACE");
            Map(m => m.M_OTHERRACE).Name("M_OTHERRACE");
            Map(m => m.EP_NOINT).Name("EP_NOINT");
            Map(m => m.MP_NOINT).Name("MP_NOINT");
            Map(m => m.EP_AFAM).Name("EP_AFAM");
            Map(m => m.MP_AFAM).Name("MP_AFAM");
            Map(m => m.EP_HISP).Name("EP_HISP");
            Map(m => m.MP_HISP).Name("MP_HISP");
            Map(m => m.EP_ASIAN).Name("EP_ASIAN");
            Map(m => m.MP_ASIAN).Name("MP_ASIAN");
            Map(m => m.EP_AIAN).Name("EP_AIAN");
            Map(m => m.MP_AIAN).Name("MP_AIAN");
            Map(m => m.EP_NHPI).Name("EP_NHPI");
            Map(m => m.MP_NHPI).Name("MP_NHPI");
            Map(m => m.EP_TWOMORE).Name("EP_TWOMORE");
            Map(m => m.MP_TWOMORE).Name("MP_TWOMORE");
            Map(m => m.EP_OTHERRACE).Name("EP_OTHERRACE");
            Map(m => m.MP_OTHERRACE).Name("MP_OTHERRACE");
        }
    }

    /**
     * @brief Holds both the raw score (from "SPL_THEMES" column) and fractional ranking ("RPL_THEMES").
     */
    internal class SviScore
    {
        internal double rawScore { get; }
        internal double rank { get; }

        internal SviScore(string rawStr, string rankingStr)
        {
            if (double.TryParse(rawStr, out double dScore))
            {
                rawScore = dScore;
            }

            // The California-only table reports ranking in interger percents, but the all-US table uses fractions.
            if (rankingStr.Contains("%"))
            {
                if (int.TryParse(rankingStr.TrimEnd('%'), out int iRank))
                {
                    // Convert 3% to 0.03
                    rank = iRank * 0.01;
                }
            }
            else
            {
                if (double.TryParse(rankingStr, out double dRank))
                {
                    rank = dRank;
                }
            }
        }
    }

    /**
     * @brief Builds & uses a Dictionary that maps the FIPS code to the SVI information.
     */
    internal class SviTable
    {
        private Microsoft.Office.Interop.Excel.Application application;
        private Dictionary<ulong, SviModel> sviTable;
        private string filePattern;
        private char fileSeparator;
        private string sviScope;

        internal bool ready { get; } = false;

        // https://stackoverflow.com/a/28546547/18749636
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(
            MethodBase.GetCurrentMethod().DeclaringType
        );

        internal SviTable(string year)
        {
            // Do we want California-only SVI? Or all US?
            GetSviFileNameAndSeparator(year);

            if (string.IsNullOrEmpty(filePattern))
            {
                return;
            }

            sviTable = new Dictionary<ulong, SviModel>();
            var assembly = Assembly.GetExecutingAssembly();
            var resourceName = assembly.GetManifestResourceNames().Single(str => str.EndsWith(filePattern));

            // https://joshclose.github.io/CsvHelper/getting-started/
            using (var reader = new StreamReader(assembly.GetManifestResourceStream(resourceName)))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                csv.Context.RegisterClassMap<SviModelClassMap>();
                var records = csv.GetRecords<SviModel>();

                foreach (var record in records)
                {
                    sviTable.Add(record.FIPS, record);
                }
            }

            ready = sviTable.Count > 0;

            application = Globals.ThisAddIn.Application;
            application.StatusBar = "Complete";
        }

        /// <summary>
        /// Gets either the all-USA file or just the California data.
        /// <summary>
        /// <returns>string</returns>
        private string GetSviFileName(SviScope desiredScope, string year)
        {
            string filePattern = string.Empty;

            switch (desiredScope)
            {
                case SviScope.California:
                    sviScope = "California";

                    switch (year)
                    {
                        case "2010":
                            filePattern = "California_2020.csv";
                            break;

                        case "2020":
                            filePattern = "California_2022.csv";
                            break;

                        default:
                            throw new ArgumentOutOfRangeException(year, "Expected either 2010 or 2020.");
                    }

                    break;

                case SviScope.USA:
                    sviScope = "USA";

                    switch (year)
                    {
                        case "2010":
                            filePattern = "SVI_2020_US.csv";
                            break;

                        case "2020":
                            filePattern = "SVI_2022_US.csv";
                            break;

                        default:
                            throw new ArgumentOutOfRangeException(year, "Expected either 2010 or 2020.");
                    }

                    break;
            }

            return filePattern;
        }

        /// <summary>
        /// Gets file separator for
        /// the all-USA file (comma-separated) or just the California data (tab-separated).
        /// <summary>
        /// <returns>string</returns>
        private char GetSviFileSeparator(SviScope desiredScope, string year)
        {
            char fileSeparator = '\0';

            switch (desiredScope)
            {
                case SviScope.California:

                    switch (year)
                    {
                        case "2010":
                            fileSeparator = ',';
                            break;
                        case "2020":
                            fileSeparator = ',';
                            break;
                        default:
                            throw new ArgumentOutOfRangeException(year, "Expected either 2010 or 2020.");
                    }

                    break;
                case SviScope.USA:
                    fileSeparator = ',';
                    break;
            }

            return fileSeparator;
        }

        /// <summary>
        /// Sets the class properties depending on which data file we want.
        /// <summary>
        /// <returns>SviScope enum</returns>
        private void GetSviFileNameAndSeparator(string year)
        {
            SviScope desiredScope = GetUserPreference();
            filePattern = GetSviFileName(desiredScope, year);
            fileSeparator = GetSviFileSeparator(desiredScope, year);
        }

        /// <summary>
        /// Asks the user if they want all-USA file or just California data.
        /// <summary>
        /// <returns>SviScope enum</returns>
        private SviScope GetUserPreference()
        {
            using (ChooseAOrBForm form = new ChooseAOrBForm("Choose which SVI data set.", "California", "USA"))
            {
                var result = form.ShowDialog();

                if (result == DialogResult.OK)
                {
                    if (SviScope.TryParse(form.choice, out SviScope scope))
                    {
                        return scope;
                    }
                }
            }

            return SviScope.Unknown;
        }

        /// <summary>
        /// Returns the rank for the census tract provided.
        /// <summary>
        /// <param name="tract">ulong census tract number.</param>
        /// <returns>double?</returns>
        internal double? rank(ulong tract)
        {
            try
            {
                return sviTable[tract].RPL_THEMES;
            }
            catch (KeyNotFoundException)
            {
                return null;
            }
        }

        /// <summary>
        /// Returns the raw score for the census tract provided.
        /// <summary>
        /// <param name="tract">ulong census tract number.</param>
        /// <returns>double?</returns>
        internal double? raw(ulong tract)
        {
            try 
            { 
                return sviTable[tract].SPL_THEMES; 
            }
            catch (KeyNotFoundException)
            {
                return null;
            }
            
        }

        internal string Scope()
        {
            return sviScope;
        }
    }
}
